title: "HowieWiki"
description: "A personal knowledge base by Howie Guan"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: "https://howieguan0.github.io/HowieWiki"

aux_links:
  "GitHub Repository":
    - "//github.com/howieguan0/HowieWiki"
