title: "HowieWiki"
description: "Personal knowledge base by Howie Guan"
theme: just-the-docs

url: "https://howieguan0.github.io"
baseurl: "/HowieWiki"

defaults:
  - scope:
      path: ""        # all files
      type: "pages"
    values:
      layout: "default"
